spring:
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
        web-application-type: none
    application:
        name: console
    profiles:
        active: local
    shell:
        debug:
            enabled: true
        interactive:
            enabled: true
