server:
    port: 8181
spring:
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
        web-application-type: servlet
    servlet:
        multipart:
            enabled: true
            max-file-size: 1000MB
            max-request-size: 1000MB
    application:
        name: app-server
    profiles:
        active: local
